-- WheelDesk Layer 6I — Shadow Forward Validation

BEGIN;

CREATE TABLE IF NOT EXISTS zero_dte_shadow_trades (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  trade_date date NOT NULL,
  signal_id text NOT NULL,
  strategy text NOT NULL,
  setup_key text NOT NULL,
  strategy_label text,
  legs jsonb NOT NULL DEFAULT '[]'::jsonb,
  state text NOT NULL DEFAULT 'open',

  signal_time timestamptz NOT NULL,
  signal_candle_time bigint,
  entry_score numeric,
  minimum_entry_score numeric,
  time_regime text,
  short_delta_abs numeric,
  short_distance_points numeric,
  entry_mark_credit numeric,
  entry_sellable_credit numeric NOT NULL,
  signal_peak_credit numeric,
  premium_expansion_pct numeric,
  premium_rollover_pct numeric,
  premium_crest_status text,
  price_rejection_score numeric,
  remaining_move_points numeric,
  max_risk_dollars numeric,
  width_points numeric,
  entry_event_risk text,
  entry_range_consumption_pct numeric,
  entry_map_phase text,
  entry_map_center numeric,
  entry_rail_breached text,

  path_direction text,
  path_confidence numeric,
  path_flow_source text,
  path_terminal_trough numeric,
  path_terminal_crest numeric,

  last_sample_at timestamptz,
  current_mark_credit numeric,
  current_buyback_debit numeric,
  max_mark_credit numeric,
  min_buyback_debit numeric,
  max_adverse_excursion_dollars numeric NOT NULL DEFAULT 0,
  max_favorable_excursion_dollars numeric NOT NULL DEFAULT 0,

  hit_short_strike boolean NOT NULL DEFAULT false,
  hit_one_point_five_x boolean NOT NULL DEFAULT false,
  hit_two_x boolean NOT NULL DEFAULT false,
  ran_to_max_loss boolean NOT NULL DEFAULT false,

  exit_time timestamptz,
  exit_reason text,
  exit_buyback_debit numeric,
  exit_score numeric,
  exit_emergency boolean NOT NULL DEFAULT false,
  pnl_conservative_dollars numeric,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uq_zero_dte_shadow_signal UNIQUE (user_id, signal_id)
);

CREATE INDEX IF NOT EXISTS idx_zero_dte_shadow_trade_date
  ON zero_dte_shadow_trades(user_id, trade_date, signal_time);

CREATE INDEX IF NOT EXISTS idx_zero_dte_shadow_open
  ON zero_dte_shadow_trades(user_id, trade_date, state)
  WHERE state = 'open';

CREATE TABLE IF NOT EXISTS zero_dte_shadow_trade_samples (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shadow_trade_id uuid NOT NULL REFERENCES zero_dte_shadow_trades(id) ON DELETE CASCADE,
  trade_date date NOT NULL,
  sampled_at timestamptz NOT NULL,
  spx_price numeric NOT NULL,
  mark_credit numeric,
  sellable_credit numeric,
  buyback_debit numeric,
  pnl_conservative_dollars numeric,
  short_distance_points numeric,
  lifecycle text,
  exit_score numeric,
  emergency_exit boolean NOT NULL DEFAULT false,
  path_threat boolean NOT NULL DEFAULT false,
  hit_short_strike boolean NOT NULL DEFAULT false,
  hit_one_point_five_x boolean NOT NULL DEFAULT false,
  hit_two_x boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT uq_zero_dte_shadow_sample UNIQUE (shadow_trade_id, sampled_at)
);

CREATE INDEX IF NOT EXISTS idx_zero_dte_shadow_samples_time
  ON zero_dte_shadow_trade_samples(trade_date, sampled_at);

ALTER TABLE zero_dte_shadow_trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE zero_dte_shadow_trade_samples ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS zero_dte_shadow_trades_owner ON zero_dte_shadow_trades;
CREATE POLICY zero_dte_shadow_trades_owner
  ON zero_dte_shadow_trades
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS zero_dte_shadow_samples_owner ON zero_dte_shadow_trade_samples;
CREATE POLICY zero_dte_shadow_samples_owner
  ON zero_dte_shadow_trade_samples
  FOR ALL
  USING (
    EXISTS (
      SELECT 1
      FROM zero_dte_shadow_trades t
      WHERE t.id = shadow_trade_id
        AND t.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM zero_dte_shadow_trades t
      WHERE t.id = shadow_trade_id
        AND t.user_id = auth.uid()
    )
  );

-- Forward-validation view: one row per shadow signal with conservative outcomes
-- nearest to +5m/+15m/+30m and the final engine-managed result.
CREATE OR REPLACE VIEW zero_dte_shadow_trade_outcomes AS
SELECT
  t.id,
  t.user_id,
  t.trade_date,
  t.strategy,
  t.setup_key,
  t.signal_time,
  t.entry_score,
  t.minimum_entry_score,
  t.time_regime,
  t.short_delta_abs,
  t.short_distance_points,
  t.entry_mark_credit,
  t.entry_sellable_credit,
  t.signal_peak_credit,
  t.premium_expansion_pct,
  t.premium_rollover_pct,
  t.premium_crest_status,
  t.price_rejection_score,
  t.remaining_move_points,
  t.entry_range_consumption_pct,
  t.path_direction,
  t.path_confidence,
  t.path_flow_source,
  t.max_adverse_excursion_dollars,
  t.max_favorable_excursion_dollars,
  t.hit_short_strike,
  t.hit_one_point_five_x,
  t.hit_two_x,
  t.ran_to_max_loss,
  s5.pnl_conservative_dollars AS pnl_5m_dollars,
  s15.pnl_conservative_dollars AS pnl_15m_dollars,
  s30.pnl_conservative_dollars AS pnl_30m_dollars,
  t.pnl_conservative_dollars AS pnl_exit_dollars,
  CASE
    WHEN GREATEST(COALESCE(t.signal_peak_credit, 0), COALESCE(t.max_mark_credit, 0)) > 0
    THEN t.entry_mark_credit / GREATEST(COALESCE(t.signal_peak_credit, 0), COALESCE(t.max_mark_credit, 0)) * 100
    ELSE NULL
  END AS peak_capture_efficiency_pct,
  t.exit_reason,
  t.exit_time
FROM zero_dte_shadow_trades t
LEFT JOIN LATERAL (
  SELECT s.pnl_conservative_dollars
  FROM zero_dte_shadow_trade_samples s
  WHERE s.shadow_trade_id = t.id
    AND s.sampled_at >= t.signal_time + interval '5 minutes'
  ORDER BY s.sampled_at
  LIMIT 1
) s5 ON TRUE
LEFT JOIN LATERAL (
  SELECT s.pnl_conservative_dollars
  FROM zero_dte_shadow_trade_samples s
  WHERE s.shadow_trade_id = t.id
    AND s.sampled_at >= t.signal_time + interval '15 minutes'
  ORDER BY s.sampled_at
  LIMIT 1
) s15 ON TRUE
LEFT JOIN LATERAL (
  SELECT s.pnl_conservative_dollars
  FROM zero_dte_shadow_trade_samples s
  WHERE s.shadow_trade_id = t.id
    AND s.sampled_at >= t.signal_time + interval '30 minutes'
  ORDER BY s.sampled_at
  LIMIT 1
) s30 ON TRUE;

COMMIT;
