import { NextRequest, NextResponse } from "next/server";
import { getAuthenticatedUserFromRequest } from "../../../../lib/billing/auth-request";
import { supabaseServer } from "../../../../lib/supabase-server";
import type { ZeroDteExecutionMemory } from "../../../../lib/zeroDteExecutionIntelligence";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const err=(e:unknown,s=500)=>NextResponse.json({ok:false,error:e instanceof Error?e.message:String(e)},{status:s});
const n=(v:any)=>typeof v==="number"&&Number.isFinite(v)?v:v!=null&&Number.isFinite(Number(v))?Number(v):null;
async function memory(userId:string,tradeDate:string):Promise<ZeroDteExecutionMemory>{
 const {data:day}=await supabaseServer.from("zero_dte_execution_trade_days").select("id").eq("user_id",userId).eq("trade_date",tradeDate).eq("symbol","SPX").maybeSingle();
 if(!day)return {tradeDate,tradeDayId:null,samples:[],position:null,closedTrades:[],cooldownUntil:null};
 const [{data:samples},{data:open},{data:closed}]=await Promise.all([
  supabaseServer.from("zero_dte_execution_score_history").select("sampled_at,spx_price,if_credit,sell_score,buyback_score,spring_probability,opportunity_score").eq("user_id",userId).eq("trade_day_id",day.id).order("sampled_at",{ascending:true}).limit(240),
  supabaseServer.from("zero_dte_execution_positions").select("*").eq("user_id",userId).eq("trade_day_id",day.id).eq("state","open").maybeSingle(),
  supabaseServer.from("zero_dte_execution_positions").select("*").eq("user_id",userId).eq("trade_day_id",day.id).eq("state","closed").order("exit_time",{ascending:false}).limit(100)
 ]);
 const pos=open?{id:open.id,openedAt:open.entry_time,entryCredit:Number(open.entry_credit),quantity:Number(open.contracts),entrySellScore:Number(open.entry_sell_score??0),entrySpringProbability:Number(open.entry_spring_probability??0),entryOpportunityScore:Number(open.entry_opportunity_score??0),side:open.setup_side}:null;
 const trades=(closed??[]).map((x:any)=>({id:x.id,openedAt:x.entry_time,entryCredit:Number(x.entry_credit),quantity:Number(x.contracts),entrySellScore:Number(x.entry_sell_score??0),entrySpringProbability:Number(x.entry_spring_probability??0),entryOpportunityScore:Number(x.entry_opportunity_score??0),side:x.setup_side,closedAt:x.exit_time,exitDebit:Number(x.exit_debit??0),buybackScore:Number(x.exit_buyback_score??0),pnlDollars:Number(x.realized_pnl??0),durationMinutes:Number(x.duration_minutes??0)}));
 const cooldownUntil=trades[0]?.closedAt?new Date(Date.parse(trades[0].closedAt)+15*60000).toISOString():null;
 return {tradeDate,tradeDayId:day.id,samples:(samples??[]).map((x:any)=>({timestamp:x.sampled_at,spot:Number(x.spx_price),credit:Number(x.if_credit),sellScore:Number(x.sell_score),buybackScore:Number(x.buyback_score),springProbability:Number(x.spring_probability),opportunityScore:Number(x.opportunity_score)})),position:pos as any,closedTrades:trades as any,cooldownUntil};
}
async function dayId(userId:string,b:any){const m=b.openingMap,p=b.openingPlan,r=b.recommendation;const payload={user_id:userId,trade_date:b.tradeDate,symbol:"SPX",expiration_date:b.expirationDate,opening_if_center:m.center,opening_if_width:50,lower_wing:m.lowerWing,upper_wing:m.upperWing,opening_put_wall:m.putWall,opening_call_wall:m.callWall,opening_gravity:m.gravity,locked_put_short:p?.put?.shortStrike??null,locked_put_long:p?.put?.longStrike??null,locked_call_short:p?.call?.shortStrike??null,locked_call_long:p?.call?.longStrike??null,opening_if_credit:b.sample?.credit??null,opening_dealer_pressure:r.dealerPressure,opening_pin_score:r.confidenceScore,updated_at:new Date().toISOString()};const {data,error}=await supabaseServer.from("zero_dte_execution_trade_days").upsert(payload,{onConflict:"user_id,trade_date,symbol",ignoreDuplicates:false}).select("id").single();if(error)throw error;return data.id;}
export async function GET(req:NextRequest){try{const u=await getAuthenticatedUserFromRequest(req);const d=req.nextUrl.searchParams.get("tradeDate");if(!d)return err("Missing tradeDate",400);return NextResponse.json({ok:true,memory:await memory(u.id,d)});}catch(e){return err(e,401)}}
export async function POST(req:NextRequest){try{const u=await getAuthenticatedUserFromRequest(req);const b=await req.json();if(!b.tradeDate)return err("Missing tradeDate",400);
 if(b.action==="sample"){const id=await dayId(u.id,b);const {data:open}=await supabaseServer.from("zero_dte_execution_positions").select("id").eq("user_id",u.id).eq("trade_day_id",id).eq("state","open").maybeSingle();const s=b.sample;const {error}=await supabaseServer.from("zero_dte_execution_score_history").upsert({user_id:u.id,trade_day_id:id,position_id:open?.id??null,sampled_at:s.timestamp,spx_price:s.spot,if_credit:s.credit,sell_score:s.sellScore,buyback_score:s.buybackScore,spring_probability:s.springProbability,opportunity_score:s.opportunityScore,dealer_pressure:b.recommendation.dealerPressure,strike_flow_state:b.flowState,premium_efficiency:b.read.currentCredit?Math.min(100,b.read.currentCredit/50*100):null,peak_credit:b.read.peakCredit,credit_velocity:b.read.premiumVelocityPerMinute,edge:b.read.edge},{onConflict:"user_id,trade_day_id,sampled_at"});if(error)throw error;return NextResponse.json({ok:true,memory:await memory(u.id,b.tradeDate)});}
 const mem=await memory(u.id,b.tradeDate);if(!mem.tradeDayId)return err("Opening trade day has not been persisted yet",409);
 if(b.action==="open"){const {error}=await supabaseServer.from("zero_dte_execution_positions").insert({user_id:u.id,trade_day_id:mem.tradeDayId,strategy:"iron_fly",state:"open",entry_time:b.entryTime,entry_credit:n(b.entryCredit),contracts:Math.max(1,Math.floor(n(b.contracts)??1)),setup_side:b.side,entry_sell_score:b.read.sellScore,entry_spring_probability:b.read.springProbability,entry_opportunity_score:b.read.opportunityScore});if(error)throw error;return NextResponse.json({ok:true,memory:await memory(u.id,b.tradeDate)});}
 if(b.action==="close"){if(!mem.position)return err("No open IF position",409);const pnl=(mem.position.entryCredit-n(b.exitDebit)!)*100*mem.position.quantity;const minutes=Math.max(0,(Date.parse(b.exitTime)-Date.parse(mem.position.openedAt))/60000);const {error}=await supabaseServer.from("zero_dte_execution_positions").update({state:"closed",exit_time:b.exitTime,exit_debit:n(b.exitDebit),exit_buyback_score:n(b.buybackScore),realized_pnl:pnl,duration_minutes:minutes,updated_at:new Date().toISOString()}).eq("id",mem.position.id).eq("user_id",u.id);if(error)throw error;await supabaseServer.from("zero_dte_execution_exits").upsert({user_id:u.id,position_id:mem.position.id,exit_time:b.exitTime,exit_debit:n(b.exitDebit),realized_pnl:pnl,buyback_score:n(b.buybackScore),hold_minutes:minutes,reason:b.reason??null},{onConflict:"position_id"});return NextResponse.json({ok:true,memory:await memory(u.id,b.tradeDate)});}
 return err("Unknown action",400);
 }catch(e){return err(e)}}
